### PR TITLE
Implement CRL check , configure TLS_CRLCHECK option of openldap

### PR DESCRIPTION
**Pull request by sebastienblavier**
The patch consists in configuring in nslcd daemon the existing CRL interface of OpenLDAP: TLS_CRLCHECK. 
This requires TLS_CACERTDIR parameter to be set, this parameter is ignored with GNUtls and Mozilla NSS.

### CODE REVIEW

**Comment by arthurdejong** [comment]
Hi @sebastienblavier 

Thanks for your code. Can you provide a short blurb for the manual page (https://arthurdejong.org/nss-pam-ldapd/nslcd.conf.5#ssl_tls_options).

**Comment by quanah** [comment]
You may also want to check for libldap that supports LDAP_OPT_X_TLS_REQUIRE_SAN and implement that as well (See https://bugs.openldap.org/show_bug.cgi?id=9318).  This is in OpenLDAP releases 2.4.52 and later.

**Comment by sebastienblavier** [comment]
Hi @arthurdejong 

Thanks to take the time for the PR review.
Man page updated in the last commit. let me know if you have any comments.

For sure at least openLDAP and all older versions of Openldap have the `LDAP_OPT_X_TLS_CRLCHECK` options. 
CRL support is a part of cryptographic, so it will be a generic option to all ldap libraries ? This option is like tls_cacertdir ?

**Comment by arthurdejong** [comment]
Thanks @sebastienblavier, I've merged the change as 78c00f1. I included `#ifdef`s just to be sure.

**Comment by sebastienblavier** [comment]
Thanks @arthurdejong

**Pull request closed without merging**
